### ISSUE TITLE
ui bugs

### ISSUE THREAD

**Issue by golam71** [spa5k/quran_next#1]
![image](https://github.com/spa5k/quran_next/assets/74001687/554c3c92-d57d-4f9d-a937-d6ee935dbc89)
here once you click the play button you can not pause 
upon clicking it again it will just play the verse again

also when you play a ayah it just keeps playing until the surah ends 

![image](https://github.com/spa5k/quran_next/assets/74001687/d7be45a3-5d03-409e-b63d-376d45b412ec)
no idea what this cross is supposed to mean but upon clicking it auto adds clear quran 

and how do i make english font big?

**Comment by spa5k** [comment]
fixed
